### ISSUE TITLE
modid collision caused by static-content's weird repackaging.

### ISSUE THREAD

**Issue by falkreon** [Draylar/static-content#3]
Hi. It's the staticdata author.

You seem to have taken an old version of my mod, cut out the fabric dependencies, and re-wrapped it for 1.20.1 with new fabric dependencies. This is now causing modid conflicts with the current mainline staticdata.

Please just fork cottonmc staticdata and use a different modid. It's MIT, you're MIT, there shouldn't be any problems for you to just use the source with credit.

**Comment by Jamalam360** [comment]
Can confirm, this causes issues when loading Armorful and Architecture Extensions at the same time

**Comment by Draylar** [comment]
This mod wraps/bundles the latest Static Data library from (1.2.2) from 2019. It is not a fork or alternative version of Static Data. Furthermore, the latest version of this library was on _1.16.2_ - so I definitely have not re-wrapped it for 1.20.1. Could you clarify what the problem is? I'm not sure how this library would cause conflicts when the only thing it does is call the Static Data API:

https://github.com/Draylar/static-content/blob/4396866ec0ca1e22d651b8b626e8efe61a529cd0/src/main/java/draylar/staticcontent/StaticContent.java#L31-L54 

Perhaps you have the wrong person or project? I haven't updated my user-facing mods to 1.20.1 yet.

**Comment by Jamalam360** [comment]
[Armorful is using this library on 1.20.1](https://github.com/mineblock11/Armorful/blob/ad42926491e1bb1571b4801466c09d2c6f22ec2a/build.gradle#L26)

Which might make this not your issue - if you're not maintaining this library, maybe mineblock should be forking it /shrug

**Comment by Draylar** [comment]
I see what the problem is now - breaking package changes were made to Static Data going from the [CottonMC fabric version](https://github.com/CottonMC/StaticData) (`io/github/cottonmc/staticdata`) to your new [Quilt repository](https://github.com/DebuggyTeam/StaticData/tree/main/src/main/java/gay/debuggy/staticdata/impl) (`gay/debuggy/staticdata`). You are running with the Quilt version of Static Data, which will completely break any older project that depended on Static Data prior to Quilt existing. This is fully on the library's end and not mine. 

The only way for me to fix this (minus you reverting breaking package changes) would be for me to switch to the new Quilt repository as a dependency, which isn't happening. I do not support Quilt - so I will mark this as resolved and continue to bundle the old Static Data version. 

Please feel free to let me know if I am missing anything (I did my investigation quite fast and may have missed something), as I would be happy to work towards an appropriate fix with you both.

**Comment by falkreon** [comment]
Draylar, staticdata as written has dependencies and metadata which indicates that it will operate on a maximum of Minecraft 1.14.4, (see https://github.com/CottonMC/StaticData/blob/master/build.gradle#L44-L48 ) all of which are removed in a very explicit and intentional way by your mod.

- https://github.com/Draylar/static-content/blob/master/build.gradle#L26 strips the fabric-api dependency and any transitive / indirect dependencies from being seen by gradle.
- https://github.com/Draylar/static-content/blob/master/build.gradle#L45-L47 strips the fabric.mod.json, removing any dependencies from being seen by loom.

This forces the cottonmc staticdata to operate outside of its rated and intended circumstances. It is an extremely inadviseable way to use a mod, it's a really inadviseable way to use *any* library, and it's causing a crash. The existence of an incompatible 1.20.1 version of this mod was foreseeable, in fact it's virtually certain, and there is literally no reasonable fix I can make at my end. Because *you are using my modid*, I am forced to talk to you to protect my modid.

Please refrain from using cottonmc staticdata in a way that is dangerous and irresponsible for users. Please **fork the mod** and change the modid so that you don't need to resort to the hackish gradle fixes I mentioned above.

**Comment by Draylar** [comment]
Hi Falkreon - long time no see/talk, hope you are doing well! 

You are more than welcome to update the modid on your new Quilt project, _or_ change the modid of the Fabric version & submit a PR to this repo (alongside repositories using this project) with the updated version. I will be happy to merge it in once you open the PR. Thanks in advance!

**Comment by Draylar** [comment]
Okay - I had time to patch in a fix this this morning @falkreon! tl;dr:

1. Published a new version of Static Data [to my maven](https://maven.draylar.dev/#/releases/io/github/cottonmc/StaticData/1.2.0) (maybe it can go on the Cotton maven if you still have write access?) with modid `staticdata-fabric` and version "1.2.0"
2. Pushed a new version of Static Content with this new dep to [here](https://maven.draylar.dev/#/releases/draylar/static-content/1.1.0-1.18.2). You can verify the modid change by cracking open the library & checking the fabric metadata file. 

This should allow both mods to load without conflicting. Feel free to open up a new issue if you spot any other problems. Thanks again for the heads up! :)

**Comment by Draylar** [comment]
Issue report on Armorful: https://github.com/mineblock11/Armorful/issues/10

I will use this new version on my mods as well, which should solve our problem here~
